"""
Slim partial migration: push the `products` table from the local Postgres
into Railway, while preserving Railway-only rows (DailyMed, etc.).

Strategy:
- Stream from local in batches via asyncpg's prepared cursor.
- For each batch, COPY into a per-session staging temp table on Railway,
  then INSERT ... ON CONFLICT (barcode) DO NOTHING into `products`.
- product_ingredients and ingredients are NOT migrated. Per slim-partial
  decision (2026-05-26): local fast path stays local for now; Railway gets
  product identity + categories + image only, which is enough for the
  alternatives feature and Phase 1 lookup_product step.

Usage (from backend/):
    python -m scripts.migrate_products_to_railway --source usda
    python -m scripts.migrate_products_to_railway --source off --batch 20000
    python -m scripts.migrate_products_to_railway --source all
"""

from __future__ import annotations

import argparse
import asyncio
import os
import time
from typing import Any

import asyncpg
from dotenv import load_dotenv

load_dotenv()

# Source order: small to large so failures surface fast on cheap pushes.
SOURCE_ORDER = ["openfda", "usda", "obf", "off"]

# Columns to migrate. `id` is autogenerated by Railway; we never push it.
COLUMNS = [
    "barcode",
    "name",
    "brand",
    "product_type",
    "image_url",
    "nutriscore",
    "nova_group",
    "categories",
    "source",
    "last_synced_at",
    "created_at",
]

STAGING_DDL = f"""
CREATE TEMP TABLE products_stage (
    barcode         TEXT,
    name            TEXT,
    brand           TEXT,
    product_type    TEXT,
    image_url       TEXT,
    nutriscore      CHAR(1),
    nova_group      SMALLINT,
    categories      TEXT[],
    source          TEXT,
    last_synced_at  TIMESTAMPTZ,
    created_at      TIMESTAMPTZ
) ON COMMIT PRESERVE ROWS
"""

INSERT_FROM_STAGE = """
INSERT INTO products (barcode, name, brand, product_type, image_url,
                      nutriscore, nova_group, categories, source,
                      last_synced_at, created_at)
SELECT barcode, name, brand, product_type, image_url,
       nutriscore, nova_group, categories, source,
       last_synced_at, created_at
FROM products_stage
ON CONFLICT (barcode) DO NOTHING
"""


async def migrate_source(
    local: asyncpg.Connection,
    railway: asyncpg.Connection,
    source: str,
    batch_size: int,
) -> tuple[int, int]:
    """
    Push all rows for one source from local to railway. Returns
    (rows_pushed, rows_skipped_via_conflict).
    """
    # Total rows we're about to push (for progress reporting)
    total = await local.fetchval(
        "SELECT COUNT(*) FROM products WHERE source = $1", source,
    )
    if total == 0:
        print(f"  [{source.upper():>8}] 0 rows in local — skipping.")
        return 0, 0

    print(f"  [{source.upper():>8}] {total:,} rows to push (batch={batch_size:,})")
    t0 = time.perf_counter()

    # One persistent staging table per source migration. Truncated each batch.
    await railway.execute(STAGING_DDL)

    pushed = 0
    last_id = -1
    batch_no = 0

    while True:
        rows = await local.fetch(
            f"""
            SELECT id, {", ".join(COLUMNS)}
            FROM products
            WHERE source = $1 AND id > $2
            ORDER BY id
            LIMIT {batch_size}
            """,
            source, last_id,
        )
        if not rows:
            break

        # Strip the `id` column before pushing — Railway autogenerates its own.
        records = [tuple(r[c] for c in COLUMNS) for r in rows]
        last_id = rows[-1]["id"]

        # COPY into staging, then INSERT ... ON CONFLICT
        async with railway.transaction():
            await railway.execute("TRUNCATE products_stage")
            await railway.copy_records_to_table(
                "products_stage", records=records, columns=COLUMNS,
            )
            inserted_result = await railway.execute(INSERT_FROM_STAGE)
        # `inserted_result` is like 'INSERT 0 1234' — parse out the count
        inserted_n = int(inserted_result.split()[-1])
        pushed += inserted_n
        batch_no += 1

        elapsed = time.perf_counter() - t0
        rate = (batch_no * batch_size) / max(elapsed, 0.01)
        pct = min(100.0, batch_no * batch_size / total * 100)
        eta = (total - batch_no * batch_size) / max(rate, 1)
        print(
            f"  [{source.upper():>8}] batch {batch_no:>4}: "
            f"pushed +{inserted_n:>5} "
            f"(cum {pushed:>9,}) "
            f"{pct:5.1f}% "
            f"{rate:>6.0f} rows/s "
            f"eta {eta:>6.0f}s"
        )

    skipped = (total - pushed)
    elapsed = time.perf_counter() - t0
    print(f"  [{source.upper():>8}] done in {elapsed:.1f}s — pushed {pushed:,}, "
          f"skipped {skipped:,} (already on Railway)")
    return pushed, skipped


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--source", required=True,
        help=f"one of: {', '.join(SOURCE_ORDER)}, or 'all'",
    )
    ap.add_argument("--batch", type=int, default=10000, help="batch size")
    ap.add_argument(
        "--local-db", default="postgresql:///safescan",
        help="local Postgres URL (default: postgresql:///safescan via unix socket)",
    )
    args = ap.parse_args()

    railway_url = os.environ["DATABASE_URL"]
    if "railway" not in railway_url and "rlwy" not in railway_url:
        print(f"WARNING: DATABASE_URL doesn't look like Railway: {railway_url[:60]}")

    if args.source == "all":
        sources = SOURCE_ORDER
    else:
        if args.source not in SOURCE_ORDER:
            raise SystemExit(f"unknown source {args.source!r}; expected one of {SOURCE_ORDER}")
        sources = [args.source]

    local = await asyncpg.connect(args.local_db)
    railway = await asyncpg.connect(railway_url)

    try:
        grand_pushed = 0
        grand_skipped = 0
        t0 = time.perf_counter()
        for src in sources:
            pushed, skipped = await migrate_source(local, railway, src, args.batch)
            grand_pushed  += pushed
            grand_skipped += skipped
        elapsed = time.perf_counter() - t0
        print(
            f"\n=== Migration complete in {elapsed:.1f}s ===\n"
            f"  total pushed:  {grand_pushed:>10,}\n"
            f"  total skipped: {grand_skipped:>10,} (barcode already on Railway)"
        )
    finally:
        await local.close()
        await railway.close()


if __name__ == "__main__":
    asyncio.run(main())
